# Generated by Django 6.0.5 on 2026-05-29 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserMainDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("biography", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Undisclosed"),
                        ],
                        default="U",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Main Details",
                "verbose_name_plural": "User Main Details",
                "db_table": "user_main_details",
            },
        ),
    ]
