# Generated by Django 6.0.5 on 2026-05-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_usermaindetails_is_active_usermaindetails_password_hash_refreshtoken",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="RefreshToken",
        ),
    ]
