# Generated by Django 6.0.5 on 2026-05-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaindetails',
            name='onboarding_stage',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('PROFILE_COMPLETED', 'Profile Completed'), ('PHOTOS_UPLOADED', 'Photos Uploaded'), ('INTERESTS_SELECTED', 'Interests Selected'), ('PREFERENCES_SET', 'Preferences Set'), ('COMPLETED', 'Completed')], default='ACCOUNT_CREATED', max_length=30),
        ),
    ]
