# Generated by Django 6.0.5 on 2026-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermaindetails_onboarding_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaindetails',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1, null=True),
        ),
    ]
