# Generated by Django 6.0.5 on 2026-05-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usermaindetails_interested_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaindetails',
            name='onboarding_stage',
        ),
        migrations.AddField(
            model_name='usermaindetails',
            name='onboarding_step',
            field=models.IntegerField(choices=[(0, 'Account Created'), (1, 'Basic Profile'), (2, 'Photos'), (3, 'Interests'), (4, 'Preferences'), (5, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='usermaindetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Undisclosed')], default='U', max_length=1),
        ),
    ]
