# Generated by Django 6.0.5 on 2026-05-31 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userphoto_add"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestMaster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Interest",
                "verbose_name_plural": "Interests",
                "db_table": "interest_master",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AlterField(
            model_name="usermaindetails",
            name="onboarding_step",
            field=models.IntegerField(
                choices=[
                    (0, "Account Created"),
                    (1, "Basic Profile"),
                    (2, "Photos"),
                    (3, "Biography"),
                    (4, "Interests"),
                    (5, "Preferences"),
                    (6, "Completed"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interests",
                        to="users.interestmaster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="users.usermaindetails",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Interest",
                "verbose_name_plural": "User Interests",
                "db_table": "user_interests",
                "indexes": [
                    models.Index(fields=["user"], name="idx_user_interests_user")
                ],
                "unique_together": {("user", "interest")},
            },
        ),
    ]
