# Generated by Django 6.0.5 on 2026-05-31 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_interestmaster_alter_usermaindetails_onboarding_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField()),
                ('max_age', models.PositiveSmallIntegerField()),
                ('max_distance_km', models.PositiveSmallIntegerField()),
                ('relationship_goal', models.CharField(choices=[('LONG_TERM', 'Long-term relationship'), ('CASUAL', 'Casual dating'), ('MARRIAGE', 'Marriage'), ('EXPLORING', 'Exploring')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.usermaindetails')),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
    ]
